/*
 * SHA-3-256 (FIPS 202) — Keccak-f[1600] permutation in a sponge
 * construction. Radically different from the Merkle-Damgård family
 * (MD4/5, SHA-1/2, RIPEMD): no IV, no compression-function-of-state-
 * and-block, no length padding. Instead a 1600-bit state (5×5 lanes
 * of 64 bits each) is permuted by 24 rounds, and the input is XOR'd
 * into the first `rate` bytes of the state between permutations.
 *
 * For SHA-3-256: rate = 1088 bits = 136 bytes; capacity = 512 bits.
 * Domain separator = 0x06 (FIPS 202 §B.2). Output = 256 bits (squeeze
 * the first 32 bytes of state after the final permutation).
 *
 * Compare against `hashlib.sha3_256(data).hexdigest()`.
 */
#include "hashes.h"

#define ROL64(x,n) (((uint64_t)(x) << (n)) | ((uint64_t)(x) >> (64u - (n))))

/* Round constants — first 24 from the Keccak-f[1600] step iota. */
static const uint64_t RC[24] = {
    0x0000000000000001ULL, 0x0000000000008082ULL, 0x800000000000808AULL,
    0x8000000080008000ULL, 0x000000000000808BULL, 0x0000000080000001ULL,
    0x8000000080008081ULL, 0x8000000000008009ULL, 0x000000000000008AULL,
    0x0000000000000088ULL, 0x0000000080008009ULL, 0x000000008000000AULL,
    0x000000008000808BULL, 0x800000000000008BULL, 0x8000000000008089ULL,
    0x8000000000008003ULL, 0x8000000000008002ULL, 0x8000000000000080ULL,
    0x000000000000800AULL, 0x800000008000000AULL, 0x8000000080008081ULL,
    0x8000000000008080ULL, 0x0000000080000001ULL, 0x8000000080008008ULL
};

/* rho rotation offsets. r[x][y] gives the rotation for lane (x,y).
 * Stored as a flat 25-entry table indexed by 5*y + x. */
static const uint8_t RHO[25] = {
    /* y=0 */  0,  1, 62, 28, 27,
    /* y=1 */ 36, 44,  6, 55, 20,
    /* y=2 */  3, 10, 43, 25, 39,
    /* y=3 */ 41, 45, 15, 21,  8,
    /* y=4 */ 18,  2, 61, 56, 14
};

/* pi: A'[x,y] = A[(x + 3y) mod 5, x]. Flattening idx = 5*y + x, the
 * destination lane d takes from src = 5*(d%5) + ((d%5) + 3*(d/5)) % 5.
 * Generated by:
 *   for d in range(25):
 *       x, y = d % 5, d // 5
 *       PI[d] = 5*x + (x + 3*y) % 5 */
static const uint8_t PI[25] = {
     0,  6, 12, 18, 24,
     3,  9, 10, 16, 22,
     1,  7, 13, 19, 20,
     4,  5, 11, 17, 23,
     2,  8, 14, 15, 21
};

/* Sponge state — 25 lanes × 8 bytes = 200 bytes. Static so a deep
 * call chain doesn't blow the stack on small embedded targets. */
static uint64_t S[25];
static uint64_t B[25];     /* scratch for pi/rho */
static uint64_t C_[5];     /* column parities for theta */

static void keccak_f1600(void) {
    uint8_t r, x, y;
    uint64_t D;

    for (r = 0; r < 24u; r++) {
        /* θ — column parity diffusion. */
        for (x = 0; x < 5u; x++) {
            C_[x] = S[x] ^ S[x + 5u] ^ S[x + 10u] ^ S[x + 15u] ^ S[x + 20u];
        }
        for (x = 0; x < 5u; x++) {
            D = C_[(x + 4u) % 5u] ^ ROL64(C_[(x + 1u) % 5u], 1u);
            for (y = 0; y < 25u; y += 5u) S[y + x] ^= D;
        }
        /* ρ + π — rotate each lane and shuffle positions in one pass. */
        for (x = 0; x < 25u; x++) {
            B[x] = ROL64(S[PI[x]], RHO[PI[x]]);
        }
        /* χ — non-linear row mixing. */
        for (y = 0; y < 25u; y += 5u) {
            uint64_t b0 = B[y    ], b1 = B[y + 1u], b2 = B[y + 2u],
                     b3 = B[y + 3u], b4 = B[y + 4u];
            S[y     ] = b0 ^ ((~b1) & b2);
            S[y + 1u] = b1 ^ ((~b2) & b3);
            S[y + 2u] = b2 ^ ((~b3) & b4);
            S[y + 3u] = b3 ^ ((~b4) & b0);
            S[y + 4u] = b4 ^ ((~b0) & b1);
        }
        /* ι — break round symmetry by xoring a constant into lane 0. */
        S[0] ^= RC[r];
    }
}

#define SHA3_256_RATE_BYTES  136u   /* bytes; = (1600 - 2*256) / 8 */
#define SHA3_512_RATE_BYTES   72u   /* bytes; = (1600 - 2*512) / 8 */
#define SHA3_RATE_LANES(rb)  ((uint8_t)((rb) >> 3))   /* bytes → lanes */

/* XOR `rate_lanes` 8-byte little-endian words from `src` into state. */
static void absorb_block(const uint8_t *src, uint8_t rate_lanes) {
    uint8_t i;
    /* State lanes are little-endian by FIPS 202 convention. */
    for (i = 0; i < rate_lanes; i++) {
        const uint8_t *p = src + (uint16_t)i * 8u;
        uint64_t lane = ((uint64_t)p[0])       | ((uint64_t)p[1] <<  8) |
                        ((uint64_t)p[2] << 16) | ((uint64_t)p[3] << 24) |
                        ((uint64_t)p[4] << 32) | ((uint64_t)p[5] << 40) |
                        ((uint64_t)p[6] << 48) | ((uint64_t)p[7] << 56);
        S[i] ^= lane;
    }
}

/* Shared sponge driver for SHA-3-256 and SHA-3-512 (and could be used
 * for SHA-3-384 / SHA-3-224 by passing different rate / outlen).
 * Absorbs `data[0..len)`, applies SHA-3 domain-separator padding
 * (suffix 0x06 + 0x80 on the rate-final byte), then squeezes
 * `out_bytes` bytes from the state's low end. Per FIPS 202, no extra
 * permutation is needed during squeeze as long as out_bytes <= rate. */
static void sha3_sponge(const uint8_t *data, uint16_t len,
                        uint8_t *out, uint8_t out_bytes,
                        uint8_t rate_bytes) {
    uint8_t  block[136];                /* sized for the larger of the two rates */
    uint8_t  rate_lanes = SHA3_RATE_LANES(rate_bytes);
    uint16_t off;
    uint8_t  rem, i;

    /* Init state. */
    for (i = 0; i < 25u; i++) S[i] = 0;

    /* Absorb full rate-sized blocks. */
    for (off = 0; (uint16_t)(off + rate_bytes) <= len; off += rate_bytes) {
        absorb_block(data + off, rate_lanes);
        keccak_f1600();
    }

    /* Final block: tail bytes, then SHA-3 suffix 0x06, zero pad, and
     * 0x80 on the last byte. */
    rem = (uint8_t)(len - off);
    for (i = 0; i < rem; i++) block[i] = data[off + i];
    block[rem] = 0x06u;
    for (i = (uint8_t)(rem + 1u); i < rate_bytes; i++) block[i] = 0u;
    block[rate_bytes - 1u] |= 0x80u;
    absorb_block(block, rate_lanes);
    keccak_f1600();

    /* Squeeze `out_bytes` bytes — first ceil(out_bytes/8) lanes. */
    for (i = 0; i < out_bytes; i++) {
        uint8_t lane_idx = (uint8_t)(i >> 3u);
        uint8_t byte_in_lane = (uint8_t)(i & 7u);
        out[i] = (uint8_t)(S[lane_idx] >> (byte_in_lane * 8u));
    }
}

void hash_sha3_256(const uint8_t *data, uint16_t len, uint8_t out[32]) HBENCH_BANKED {
    sha3_sponge(data, len, out, 32u, SHA3_256_RATE_BYTES);
}

void hash_sha3_512(const uint8_t *data, uint16_t len, uint8_t out[64]) HBENCH_BANKED {
    sha3_sponge(data, len, out, 64u, SHA3_512_RATE_BYTES);
}

/* Vestigial tail — the old direct sha3_256 body. Replaced by the
 * sponge-driver call above; left here only as a reference for what
 * the inlined-rate form looked like, and kept compiling but unused. */
#if 0
void hash_sha3_256_legacy(const uint8_t *data, uint16_t len, uint8_t out[32]) HBENCH_BANKED {
    uint8_t  block[SHA3_256_RATE_BYTES];
    uint16_t off;
    uint8_t  rem, i;

    for (i = 0; i < 25u; i++) S[i] = 0;

    for (off = 0; (uint16_t)(off + SHA3_256_RATE_BYTES) <= len; off += SHA3_256_RATE_BYTES) {
        absorb_block(data + off, 17u);
        keccak_f1600();
    }

    rem = (uint8_t)(len - off);
    for (i = 0; i < rem; i++) block[i] = data[off + i];
    block[rem] = 0x06u;
    for (i = (uint8_t)(rem + 1u); i < SHA3_256_RATE_BYTES; i++) block[i] = 0u;
    block[SHA3_256_RATE_BYTES - 1u] |= 0x80u;
    absorb_block(block, 17u);
    keccak_f1600();

    for (i = 0; i < 4u; i++) {
        uint64_t lane = S[i];
        out[i*8u]      = (uint8_t)(lane      );
        out[i*8u + 1u] = (uint8_t)(lane >>  8);
        out[i*8u + 2u] = (uint8_t)(lane >> 16);
        out[i*8u + 3u] = (uint8_t)(lane >> 24);
        out[i*8u + 4u] = (uint8_t)(lane >> 32);
        out[i*8u + 5u] = (uint8_t)(lane >> 40);
        out[i*8u + 6u] = (uint8_t)(lane >> 48);
        out[i*8u + 7u] = (uint8_t)(lane >> 56);
    }
}
#endif
